//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenderosMobileLanguage.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SenderosMobileLanguage.Resx.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta.
        /// </summary>
        public static string DeleteAccountButton {
            get {
                return ResourceManager.GetString("DeleteAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string DeleteAccountConfirmPassword {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que quiere eliminar su cuenta?.
        /// </summary>
        public static string DeleteAccountMessage {
            get {
                return ResourceManager.GetString("DeleteAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string DeleteAccountPassword {
            get {
                return ResourceManager.GetString("DeleteAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LandingButtonSignIn {
            get {
                return ResourceManager.GetString("LandingButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string LandingButtonSignUp {
            get {
                return ResourceManager.GetString("LandingButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Universidad Nacional de Colombia.
        /// </summary>
        public static string LandingLabelUN {
            get {
                return ResourceManager.GetString("LandingLabelUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string LoginButtonBack {
            get {
                return ResourceManager.GetString("LoginButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREA UNA CUENTA.
        /// </summary>
        public static string LoginButtonCreate {
            get {
                return ResourceManager.GetString("LoginButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LoginButtonForgot {
            get {
                return ResourceManager.GetString("LoginButtonForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string LoginEntryEmail {
            get {
                return ResourceManager.GetString("LoginEntryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LoginEntryPassword {
            get {
                return ResourceManager.GetString("LoginEntryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SENDEROS.
        /// </summary>
        public static string LoginLabelTitle {
            get {
                return ResourceManager.GetString("LoginLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UN.
        /// </summary>
        public static string LoginLabelUN {
            get {
                return ResourceManager.GetString("LoginLabelUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear lista.
        /// </summary>
        public static string MainMasterCreateList {
            get {
                return ResourceManager.GetString("MainMasterCreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta.
        /// </summary>
        public static string MainMasterDeleteAccount {
            get {
                return ResourceManager.GetString("MainMasterDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string MainMasterLogout {
            get {
                return ResourceManager.GetString("MainMasterLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar perfil.
        /// </summary>
        public static string MainMasterModifyUser {
            get {
                return ResourceManager.GetString("MainMasterModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividades.
        /// </summary>
        public static string MainMasterPlaces {
            get {
                return ResourceManager.GetString("MainMasterPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listas.
        /// </summary>
        public static string MainMasterSeeLists {
            get {
                return ResourceManager.GetString("MainMasterSeeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificación.
        /// </summary>
        public static string PlacesCalificationText {
            get {
                return ResourceManager.GetString("PlacesCalificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visitas.
        /// </summary>
        public static string PlacesVisitsText {
            get {
                return ResourceManager.GetString("PlacesVisitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string PopupAcceptButton {
            get {
                return ResourceManager.GetString("PopupAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos erróneos.
        /// </summary>
        public static string PopupMessage1Error {
            get {
                return ResourceManager.GetString("PopupMessage1Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuaro creado exitosamente.
        /// </summary>
        public static string PopupMessage1Success {
            get {
                return ResourceManager.GetString("PopupMessage1Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo eliminar la cuenta (Datos erróneos).
        /// </summary>
        public static string PopupMessage2Error {
            get {
                return ResourceManager.GetString("PopupMessage2Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta eliminada exitosamente.
        /// </summary>
        public static string PopupMessage2Success {
            get {
                return ResourceManager.GetString("PopupMessage2Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugares: .
        /// </summary>
        public static string SeeListsPlacesText {
            get {
                return ResourceManager.GetString("SeeListsPlacesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        public static string SignupAge {
            get {
                return ResourceManager.GetString("SignupAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione su edad.
        /// </summary>
        public static string SignupAgePicker {
            get {
                return ResourceManager.GetString("SignupAgePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string SignupBack {
            get {
                return ResourceManager.GetString("SignupBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string SignupConfirmPassword {
            get {
                return ResourceManager.GetString("SignupConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string SignupCreate {
            get {
                return ResourceManager.GetString("SignupCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de documento.
        /// </summary>
        public static string SignupDocument {
            get {
                return ResourceManager.GetString("SignupDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string SignupEmail {
            get {
                return ResourceManager.GetString("SignupEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género.
        /// </summary>
        public static string SignupGender {
            get {
                return ResourceManager.GetString("SignupGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        public static string SignupGenderFemale {
            get {
                return ResourceManager.GetString("SignupGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        public static string SignupGenderMale {
            get {
                return ResourceManager.GetString("SignupGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione su género.
        /// </summary>
        public static string SignupGenderPicker {
            get {
                return ResourceManager.GetString("SignupGenderPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string SignupName {
            get {
                return ResourceManager.GetString("SignupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string SignupPassword {
            get {
                return ResourceManager.GetString("SignupPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string SignupTitle {
            get {
                return ResourceManager.GetString("SignupTitle", resourceCulture);
            }
        }
    }
}
