//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenderosMobileLanguage.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SenderosMobileLanguage.Resx.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LandingButtonSignIn {
            get {
                return ResourceManager.GetString("LandingButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string LandingButtonSignUp {
            get {
                return ResourceManager.GetString("LandingButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Universidad Nacional de Colombia.
        /// </summary>
        public static string LandingLabelUN {
            get {
                return ResourceManager.GetString("LandingLabelUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string LoginButtonBack {
            get {
                return ResourceManager.GetString("LoginButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREA UNA CUENTA.
        /// </summary>
        public static string LoginButtonCreate {
            get {
                return ResourceManager.GetString("LoginButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LoginButtonForgot {
            get {
                return ResourceManager.GetString("LoginButtonForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string LoginEntryEmail {
            get {
                return ResourceManager.GetString("LoginEntryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LoginEntryPassword {
            get {
                return ResourceManager.GetString("LoginEntryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SENDEROS.
        /// </summary>
        public static string LoginLabelTitle {
            get {
                return ResourceManager.GetString("LoginLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UN.
        /// </summary>
        public static string LoginLabelUN {
            get {
                return ResourceManager.GetString("LoginLabelUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear lista.
        /// </summary>
        public static string MainMasterCreateList {
            get {
                return ResourceManager.GetString("MainMasterCreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta.
        /// </summary>
        public static string MainMasterDeleteAccount {
            get {
                return ResourceManager.GetString("MainMasterDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string MainMasterLogout {
            get {
                return ResourceManager.GetString("MainMasterLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar perfil.
        /// </summary>
        public static string MainMasterModifyUser {
            get {
                return ResourceManager.GetString("MainMasterModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugares.
        /// </summary>
        public static string MainMasterPlaces {
            get {
                return ResourceManager.GetString("MainMasterPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver listas.
        /// </summary>
        public static string MainMasterSeeLists {
            get {
                return ResourceManager.GetString("MainMasterSeeLists", resourceCulture);
            }
        }
    }
}
